#ifndef ERR_H
#define ERR_H

#define ERR_OK 0
#define ERROR_ILLEGAL_CLOCK 1
#define ERR_ILLEGAL_STATION 2
#define ERR_ILLEGAL_DRIVELEVEL 3
#define ERR_ILLEGAL_STATE_ENTERSTATE 4
#define ERR_ILLEGAL_STATE_TOFREQUENCY 5
#define ERR_ILLEGAL_SPEEDMODE_LED 6
#define ERR_ILLEGAL_SPEEDMODE_STATEFREQUENCY 7
#define ERR_ILLEGAL_CHANGE_STATEFREQUENCY 8
#define ERR_ILLEGAL_CHANGE_STATETOIF1 9
#define ERR_ILLEGAL_CHANGE_STATEIF1 10
#define ERR_ILLEGAL_CHANGE_STATETOIF2 11
#define ERR_ILLEGAL_CHANGE_STATEIF2 12
#define ERR_ILLEGAL_CHANGE_STATETODRIVELVL1 13
#define ERR_ILLEGAL_CHANGE_STATEDRIVELVL1 14
#define ERR_ILLEGAL_CHANGE_STATETODRIVELVL2 15
#define ERR_ILLEGAL_CHANGE_STATEDRIVELVL2 16
#define ERR_ILLEGAL_CHANGE_STATECHANGE 17
#define ERR_ILLEGAL_CLOCK 18
#define ERR_ILLEGAL_SPEEDMODE_TOGGLE 19
#define ERR_ILLEGAL_INJECTION 20
#define ERR_ILLEGAL_CHANGE_STATETOINJECTION 21
#define ERR_ILLEGAL_CHANGE_STATEINJECTION 22
#define ERR_STATION_LIST 23

#endif
